const users = [
  {
    id: 1,
    name: 'Odin Borson',
    username: 'allfather',
    email: 'allfather@aesir.co',
    phone: '1-770-736-8031 x56442',
    website: 'asgard.org',
  },
  {
    id: 2,
    name: 'Frigga Fjorgyn',
    username: 'frigg',
    email: 'frigg@aesir.co',
    phone: '010-692-6593 x09125',
    website: 'asgard.org',
  },
  {
    id: 3,
    name: 'Thor Odinson',
    username: 'thunder',
    email: 'thunder@lightning.co',
    phone: '1-463-123-4447',
    website: 'thursday.info',
  },
  {
    id: 4,
    name: 'Balder Odinson',
    username: 'handsomeboy',
    email: 'handsomeboy@asgard.org',
    phone: '493-170-9623 x156',
    website: 'mistletoe.biz',
  },
  {
    id: 5,
    name: 'Loki Odinson',
    username: 'lokireckless',
    email: 'Loki_Reckless@asgard.org',
    phone: '(254)954-1289',
    website: 'hela.info',
  },
  {
    id: 6,
    name: 'Týr Hymirson',
    username: 't',
    email: 'thye@agsadr.org',
    phone: '1-477-935-8478 x6430',
    website: 'tasdrg.org',
  },
  {
    id: 7,
    name: 'Sleipnir Svadilfarison',
    username: 'bitesthedust',
    email: 'speeddemon@wall.info',
    phone: '210.067.6132',
    website: 'buildthewall.com',
  },
  {
    id: 8,
    name: 'Fenrisulfr',
    username: 'fangmaster84',
    email: 'fangmaster84@hungry.me',
    phone: '586.493.6943 x140',
    website: 'hungry.me',
  },
  {
    id: 9,
    name: 'Jormungandr Lokison',
    username: 'jormunloki',
    email: 'jormunloki@roots.world',
    phone: '(775)976-6794 x41206',
    website: 'slither.io',
  },
  {
    id: 10,
    name: 'Freyja Njordr',
    username: 'pretty_tears',
    email: 'pretty_tearsg@vanir.biz',
    phone: '024-648-3804',
    website: 'vanir.biz',
  },
  {
    id: 11,
    name: 'Freyr Njordr',
    username: 'swordfan',
    email: 'swordfan@vanir.biz',
    phone: '1-770-736-8031 x56442',
    website: 'justiceforhorses.org',
  },
  {
    id: 12,
    name: 'Heimdall Odinson',
    username: 'goldenboy',
    email: 'goldenboy@asgard.org',
    phone: '493-170-9623 x156',
    website: 'caringgate.co',
  },
];

export {
  users
};
