---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragnarok
  labels:
    app: ragnarok
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: ragnarok
  template:
    metadata:
      labels:
        app: ragnarok
        version: v1
    spec:
      containers:
        - name: ragnarok
          image: rennerdigital.azurecr.io/ragnarok/ragnarok
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: "0.1"
              memory: 256m
          ports:
            - containerPort: 6006
---
apiVersion: v1
kind: Service
metadata:
  name: ragnarok-service
  labels:
    run: ragnarok-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http-web89
      port: 80
      targetPort: 6006
  selector:
    app: ragnarok